language: java

jdk:
- openjdk11

services:
- postgresql

before_script:
- psql -c 'create database tracker;' -U postgres


# используем язык java. Travis CI поддерживает другие языки тоже.
#language: java
#
#jdk:
#- openjdk11
#
#services:
#- postgresql
#
#before_script:
#- psql -c 'create database tracker;' -U postgres
#
#script: mvn clean install -Ptravis
#
#cache:
#  directories:
#  - $HOME/.m2
#
## после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
## Здесь используется сторонни сервис https://codecov.io/
#after_success:
#  - bash <(curl -s https://codecov.io/bash)
#
## Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
#notifications:
#  email:
#    recipients:
#      - parsentev@yandex.ru
#    on_success: never # default: change
#    on_failure: always # default: always